# flask-service.yaml
# 주석문 아래의 내용으로 파일 생성

apiVersion: v1
kind: Service
metadata:
  name: flask-service
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-layer-type: "nplb" # 로드 밸런서 네트워크 레이어 타입 설정
    service.beta.kubernetes.io/ncloud-load-balancer-size: "SMALL" # 로드 밸런서 부하 처리 성능
    service.beta.kubernetes.io/ncloud-load-balancer-internal: "false" # 사설 네트워크 타입의 로드 밸런서 생성 설정
    service.beta.kubernetes.io/ncloud-load-balancer-retain-public-ip-on-termination: "false" # 로드밸런서 제거 시 공인 IP 보존
    service.beta.kubernetes.io/ncloud-load-balancer-description: "Flask App Load Balancer" # 로드 밸런서 인스턴스에 대한 설명
    service.beta.kubernetes.io/ncloud-load-balancer-termination-protection: "false" # 로드 밸런서 자동 제거 방지 설정
    service.beta.kubernetes.io/ncloud-load-balancer-algorithm-type-code: "RR" # 로드 밸런서의 알고리즘 타입 설정 (Round Robin)
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
